import FormValidator, {validationObj} from "./FormValidator.js";

export const popUpProfile = document.querySelector('#user')
export const inputName = popUpProfile.querySelector('.pop-up__input_type_name')
export const inputJob = popUpProfile.querySelector('.pop-up__input_type_about')
export const popUp = document.querySelectorAll('.pop-up')
export const popUpen = document.querySelector('.pop-up')
export const popUpAddCard = document.querySelector('#add-card')
export  const closePop = document.querySelectorAll('.pop-up__close')
export const popUpAddForm = popUpAddCard.querySelector('.pop-up__form')
export const popUpProfileForm = popUpProfile.querySelector('.pop-up__form')
export const popUpInput = popUpen.querySelector('.pop-up__input')
export const buttonSave = popUpAddCard.querySelector('.pop-up__save')
export const inputPlace = popUpAddCard.querySelector('.pop-up__card_title')
export const inputPic = popUpAddCard.querySelector('.pop-up__card_link')
export const proFile = document.querySelector('.profile')
export const addButton = proFile.querySelector('.profile__add')
export const editButton = proFile.querySelector('.profile__edit')
export const avaName = proFile.querySelector('.profile__title')
export const avaJob = proFile.querySelector('.profile__subtitle')
export const formCardSpan = document.querySelectorAll('.form-input-error')
export const cardForm = '#add-card'
export const profileForm = '#user'
export const cardValidator = new FormValidator(validationObj, cardForm)
export const profileValidator = new FormValidator(validationObj, profileForm)